transformacao:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: 5432
      dbname: olist_dw
      schema: dw
      threads: 4