version: 2

sources:
  - name: olist  # Apelido da fonte
    schema: raw  # Nome real do schema no Postgres
    tables:
      - name: customers
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: products
      - name: sellers
      - name: product_category_name_translation